repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/fixtures/
      - id: end-of-file-fixer
        exclude: ^tests/fixtures/
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^tests/fixtures/
      - id: ruff-format
        exclude: ^tests/fixtures/

  - repo: local
    hooks:
      - id: pytest-coverage
        name: pytest with coverage
        entry: bash -lc 'direnv exec . pytest -q --cov=src --cov-fail-under=85'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
